# Rust formatting configuration
edition = "2021"
max_width = 100
use_small_heuristics = "Default"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true
format_strings = true
format_macro_matchers = true
use_field_init_shorthand = true
use_try_shorthand = true
match_block_trailing_comma = true
overflow_delimited_expr = "Vertical"
trailing_comma = "Vertical"
blank_lines_upper_bound = 2
imports_layout = "Vertical"
merge_derives = true
reorder_impl_items = true
newline_style = "Unix"